export interface ToolGuide {
  example: string;
  method: string;
  limitations: string;
}

const TOOL_GUIDES: Record<string, ToolGuide> = {
  'qr-gen': { example: 'Example: encode a campaign landing page or Wi-Fi network, scan the preview, then download SVG for print or PNG for screens.', method: 'The browser encodes the selected payload into a static QR image and applies the chosen error-correction and styling settings.', limitations: 'A static QR code does not redirect or provide scan analytics; the destination must remain available.' },
  'password-gen': { example: 'Example: generate a 20-character password with all character groups enabled, then copy it into a password manager.', method: 'Random characters are selected locally with browser cryptographic randomness and the selected length and character-set rules.', limitations: 'Never reuse generated credentials, and verify that the destination service accepts the selected symbols and length.' },
  'resume-builder': { example: 'Example: paste a target job description, add quantified experience bullets, review the ATS checks, and export the ATS-first PDF.', method: 'The editor assembles structured resume sections and evaluates completeness, action language, keyword coverage, and readability signals.', limitations: 'ATS behavior varies by employer; a score is guidance, not a hiring prediction or guarantee.' },
  'invoice-gen': { example: 'Example: add three line items, apply VAT or sales tax, choose the billing currency, and download a client-ready PDF.', method: 'Line-item quantities and rates are summed into a subtotal before tax, discount, and total fields are rendered.', limitations: 'Tax rules, payment terms, and legal invoice requirements differ by jurisdiction and business type.' },
  'uuid-gen': { example: 'Example: generate 25 UUIDs for test fixtures or database seed planning, then copy the newline-separated output.', method: 'The tool creates UUID values suitable for identifiers and displays them in a copy-friendly list.', limitations: 'Generated identifiers are not a replacement for a database uniqueness constraint or application-level validation.' },
  'age-calc': { example: 'Example: compare a birth date with an event date to see the exact years, months, and days between them.', method: 'Calendar components are compared in order so the result preserves date boundaries rather than using a rough year division.', limitations: 'Age conventions can differ for legal documents, time zones, leap-day birthdays, and local regulations.' },
  'bmi-calc': { example: 'Example: enter height and weight in the selected units to get BMI and the corresponding reference range.', method: 'BMI is calculated as mass divided by height squared after converting the supplied units.', limitations: 'BMI is a screening measure, not a diagnosis, and it does not account for muscle mass, age, pregnancy, or clinical context.' },
  'currency-conv': { example: 'Example: convert a travel budget from USD to EUR and record the displayed rate timestamp before making a payment decision.', method: 'The tool applies the selected exchange-rate response to the entered amount and shows the current source state when available.', limitations: 'Rates can change, providers can be unavailable, and banks or payment processors may add their own spreads and fees.' },
  'compound-interest': { example: 'Example: compare monthly and annual compounding for a starting balance plus recurring contributions over 20 years.', method: 'The future value combines the initial principal and contribution annuities using the supplied rate, period, and compounding frequency.', limitations: 'The result is a mathematical projection, not a guaranteed investment return; taxes, fees, inflation, and volatility are excluded unless entered.' },
  'crypto-roi': { example: 'Example: enter token quantity, buy price, sell price, and trading fees to see net profit and ROI.', method: 'Cost basis and proceeds are calculated from user-supplied prices and quantity, then fees are deducted from the result.', limitations: 'The calculator does not fetch prices, account for slippage, tax treatment, staking, or predict future market performance.' },
  'mortgage-amortization': { example: 'Example: compare a 30-year loan with and without an extra monthly principal payment to see interest savings.', method: 'The fixed-rate payment formula is applied across the term and the balance is reduced month by month to estimate interest and principal.', limitations: 'Real payments may include taxes, insurance, points, variable rates, escrow, fees, and lender-specific rounding.' },
  'salary-after-tax': { example: 'Example: enter gross annual pay, deductions, and an effective tax estimate to approximate monthly take-home pay.', method: 'Gross income is reduced by user-supplied deductions and an effective tax rate rather than a hardcoded jurisdiction table.', limitations: 'This is not tax advice or a filing calculation; local brackets, credits, benefits, and payroll rules can materially change the result.' },
  'freelance-rate': { example: 'Example: combine an annual income goal, expenses, paid leave, and realistic billable hours to set an hourly floor.', method: 'The target revenue is divided by expected billable capacity after accounting for non-billable time and operating costs.', limitations: 'Your market, scope, taxes, currency, demand, and contract risk may justify a different rate or pricing model.' },
  'investment-return': { example: 'Example: compare an investment’s start value and end value with fees and dates to estimate profit, ROI, and annualized return.', method: 'The tool compares net start and end values and annualizes the change over the supplied holding period.', limitations: 'Annualized return can hide volatility and timing; it is not a forecast and excludes taxes or cash-flow timing unless supplied.' },
  'percentage-calc': { example: 'Example: calculate what 18 is as a percentage of 240, or compare the percentage change between two prices.', method: 'The selected percentage relationship is applied directly to the supplied values with clear intermediate labels.', limitations: 'Percentage change and percentage-point change are different concepts; choose the operation that matches the question.' },
  'sitemap-generator': { example: 'Example: paste one absolute canonical URL per line and download an XML sitemap for a small site.', method: 'URLs are normalized and escaped into the XML sitemap protocol format with optional priority and change-frequency fields.', limitations: 'A sitemap is a discovery hint, not an indexing guarantee; submit it through the site’s verified search-console property.' },
  'htaccess-generator': { example: 'Example: redirect an old article path to its replacement with a permanent 301 rule while preserving query-string behavior.', method: 'The generator emits Apache rewrite directives from the old path, destination, and redirect type.', limitations: 'Apache configuration varies by host; test in staging and avoid redirect chains or loops.' },
  'robots-generator': { example: 'Example: allow all crawlers, disallow a private admin path, and point crawlers to the XML sitemap.', method: 'The selected user-agent, allow, disallow, and sitemap directives are serialized into root-level robots.txt syntax.', limitations: 'robots.txt is not an access-control system and should never be used to protect confidential data.' },
  'domain-age': { example: 'Example: enter example.com to inspect public RDAP registration date, estimated age, and registry status when available.', method: 'The browser requests public RDAP data and derives an approximate age from the returned registration event.', limitations: 'RDAP coverage and fields vary by registry; this tool does not provide a third-party SEO authority score.' },
  'social-share': { example: 'Example: enter a blog URL and title to create copy-ready share links for Facebook, X, and LinkedIn.', method: 'The tool URL-encodes the page URL and message parameters into each network’s documented share-link pattern.', limitations: 'Final previews are controlled by each network’s crawler and the destination page’s Open Graph metadata.' },
  'json-csv': { example: 'Example: paste an array of customer records and download a CSV with escaped commas, quotes, and consistent columns.', method: 'The parser checks JSON structure, discovers object keys, and escapes each value according to CSV rules.', limitations: 'Nested objects are serialized as JSON text and spreadsheet software may interpret formulas or large numbers differently.' },
  'regex-cheat': { example: 'Example: test an email-like pattern against several lines and inspect each match before adding it to code.', method: 'The browser compiles the supplied expression with selected flags and executes it against the sample text.', limitations: 'Regex dialects differ across JavaScript, PCRE, RE2, and other engines; verify the final target runtime.' },
  'sql-formatter': { example: 'Example: paste a dense SELECT with joins and nested conditions to create a readable review copy.', method: 'The formatter tokenizes common SQL punctuation and keywords and inserts indentation and line breaks.', limitations: 'Formatting does not validate schema, permissions, query plans, or vendor-specific syntax.' },
  'yaml-validator': { example: 'Example: paste a CI configuration and inspect a precise parser message before committing it.', method: 'A real YAML parser reads the document without executing application commands and returns normalized output or an error.', limitations: 'Parsing success does not guarantee that a specific CI, Kubernetes, or application schema accepts the document.' },
  'crontab-generator': { example: 'Example: choose every weekday at 09:00 and copy the five-field cron expression with its plain-language summary.', method: 'The selected minute, hour, day, month, and weekday values are assembled into standard cron field order.', limitations: 'Cron implementations differ, and schedules run in the host machine’s time zone unless configured otherwise.' },
  'timezone-converter': { example: 'Example: convert a remote team meeting from America/New_York to Europe/London and Asia/Kolkata.', method: 'IANA time-zone rules are applied to the selected local date and time, including daylight-saving transitions.', limitations: 'Historical and future offset rules can change; confirm critical appointments with the calendar system used by the team.' },
  'svg-png': { example: 'Example: paste an SVG logo, set a transparent or solid background, and export a PNG for a presentation.', method: 'The SVG markup is rendered to a browser canvas and converted to a PNG data output locally.', limitations: 'External fonts, linked images, unsupported filters, and very large canvases can affect rendering.' },
  'flexbox-generator': { example: 'Example: choose row direction, centered alignment, wrapping, and a gap, then copy the generated CSS.', method: 'Visual controls map directly to CSS flex container properties and update a live preview.', limitations: 'The generated container rules do not define child sizing, content semantics, or responsive breakpoints by themselves.' },
  'utm-builder': { example: 'Example: build a newsletter URL with source=email, medium=owned, and campaign=spring-launch.', method: 'The builder appends URL-encoded UTM parameters while preserving the destination URL’s existing query string.', limitations: 'Analytics platforms must be configured to read the same naming conventions; inconsistent casing fragments reporting.' },
  'subnet-calc': { example: 'Example: enter 192.168.10.0/24 to see the network address, broadcast address, host range, and address count.', method: 'The IPv4 address is converted to a 32-bit value and masked with the CIDR prefix to derive network boundaries.', limitations: 'This is an IPv4 calculator and does not configure routers, validate VLAN policy, or replace network documentation.' },
};

export function getToolGuide(toolId: string) {
  return TOOL_GUIDES[toolId];
}
