import type { Tool, ToolCategory, QuickFilter } from '../types';

export const TOOL_CATEGORIES: ToolCategory[] = [
  { id: 'generator', label: 'Generator Tools', short: 'Generator' },
  { id: 'calculator', label: 'Finance & Calculator Tools', short: 'Calculator' },
  { id: 'developer', label: 'Developer & Webmaster Tools', short: 'Developer' },
  { id: 'image', label: 'Visual Tools', short: 'Image' },
];

export const TOOLS: Tool[] = [
  { id: 'qr-gen', name: 'QR Code Generator', description: 'Create downloadable QR codes for links, contact cards, events, and campaigns.', category: 'generator', slug: '/generator/qr', icon: 'QrCode', badge: 'Popular', tag: { label: 'No upload', tone: 'violet' }, highlight: 'Fast preview', keywords: ['qr', 'barcode', 'link'] },
  { id: 'password-gen', name: 'Secure Password Generator', description: 'Generate strong passwords locally in your browser with transparent length and character controls.', category: 'generator', slug: '/generator/password', icon: 'Lock', tag: { label: 'Private', tone: 'green' }, highlight: 'Runs locally', keywords: ['password', 'security', 'generator'] },
  { id: 'resume-builder', name: 'Resume Builder', description: 'Build a readable ATS-first resume with templates, live preview, demo data, and PDF export.', category: 'generator', slug: '/generator/resume', icon: 'FilePen', badge: 'Popular', tag: { label: 'No upload', tone: 'violet' }, highlight: '20 templates', keywords: ['resume', 'cv', 'builder', 'ats'] },
  { id: 'invoice-gen', name: 'Invoice Generator', description: 'Create clean invoices with line items, totals, tax, and PDF-ready output.', category: 'generator', slug: '/generator/invoice', icon: 'Receipt', tag: { label: 'No upload', tone: 'violet' }, highlight: 'PDF-ready', keywords: ['invoice', 'billing'] },
  { id: 'uuid-gen', name: 'UUID Generator', description: 'Generate UUIDs in bulk, copy them quickly, and use them in APIs, databases, and tests.', category: 'generator', slug: '/generator/uuid', icon: 'Fingerprint', tag: { label: 'No upload', tone: 'violet' }, highlight: 'Bulk output', keywords: ['uuid', 'guid', 'developer'] },
  { id: 'age-calc', name: 'Age Calculator', description: 'Calculate exact age and date differences in years, months, days, hours, and minutes.', category: 'calculator', slug: '/calculator/age', icon: 'Calendar', tag: { label: 'No upload', tone: 'violet' }, highlight: 'Exact dates', keywords: ['age', 'date', 'birthday'] },
  { id: 'bmi-calc', name: 'BMI Calculator', description: 'Estimate BMI and show the calculation assumptions clearly for a quick health reference.', category: 'calculator', slug: '/calculator/bmi', icon: 'Activity', tag: { label: 'No upload', tone: 'violet' }, highlight: 'Transparent math', keywords: ['bmi', 'health', 'weight'] },
  { id: 'currency-conv', name: 'Currency Converter', description: 'Convert currencies using live rates when available and show the rate timestamp and source state.', category: 'calculator', slug: '/calculator/currency', icon: 'TrendingUp', tag: { label: 'Live rate', tone: 'green' }, highlight: 'Live data', keywords: ['currency', 'exchange', 'forex'] },
  { id: 'compound-interest', name: 'Compound Interest Calculator', description: 'Explore long-term growth from an initial amount, recurring contributions, rate, and compounding frequency.', category: 'calculator', slug: '/calculator/compound-interest', icon: 'TrendingUp', tag: { label: 'Finance', tone: 'green' }, highlight: 'Growth breakdown', keywords: ['compound', 'interest', 'investment', 'savings'] },
  { id: 'crypto-roi', name: 'Crypto ROI & Profit Calculator', description: 'Calculate cost basis, proceeds, fees, profit or loss, and ROI from supplied token prices.', category: 'calculator', slug: '/calculator/crypto-roi', icon: 'Bitcoin', badge: 'Crypto', tag: { label: 'Estimate', tone: 'orange' }, highlight: 'Fee-aware', keywords: ['crypto', 'bitcoin', 'roi', 'profit'] },
  { id: 'mortgage-amortization', name: 'Mortgage Amortization Calculator', description: 'Estimate fixed-rate payments, total interest, and the impact of extra monthly principal.', category: 'calculator', slug: '/calculator/mortgage', icon: 'Home', tag: { label: 'Finance', tone: 'green' }, highlight: 'Payment schedule', keywords: ['mortgage', 'loan', 'amortization', 'home'] },
  { id: 'salary-after-tax', name: 'Salary After Tax Calculator', description: 'Estimate take-home pay from gross income, deductions, an estimated tax rate, and region.', category: 'calculator', slug: '/calculator/salary-after-tax', icon: 'WalletCards', tag: { label: 'Estimate', tone: 'orange' }, highlight: 'Tax-aware inputs', keywords: ['salary', 'tax', 'paycheck', 'income'] },
  { id: 'freelance-rate', name: 'Freelance Hourly Rate Calculator', description: 'Turn income goals, business costs, working time, and billable capacity into a sustainable hourly rate.', category: 'calculator', slug: '/calculator/freelance-rate', icon: 'BriefcaseBusiness', tag: { label: 'Remote work', tone: 'violet' }, highlight: 'Capacity-aware', keywords: ['freelance', 'hourly', 'rate', 'remote'] },
  { id: 'investment-return', name: 'Investment Return Calculator', description: 'Compare start and end values to estimate profit, ROI, fees, and annualized return.', category: 'calculator', slug: '/calculator/investment-return', icon: 'ChartNoAxesCombined', tag: { label: 'Estimate', tone: 'green' }, highlight: 'CAGR view', keywords: ['investment', 'return', 'cagr', 'profit'] },
  { id: 'percentage-calc', name: 'Percentage Calculator', description: 'Calculate percentage shares, percentage change, and the difference between two values.', category: 'calculator', slug: '/calculator/percentage', icon: 'Percent', tag: { label: 'No upload', tone: 'violet' }, highlight: 'Quick math', keywords: ['percentage', 'percent', 'change'] },
  { id: 'sitemap-generator', name: 'XML Sitemap Generator', description: 'Turn absolute URLs into UTF-8 XML sitemap output with canonical URL guidance.', category: 'developer', slug: '/developer/sitemap', icon: 'Map', tag: { label: 'SEO', tone: 'green' }, highlight: 'Search-ready', keywords: ['sitemap', 'xml', 'seo'] },
  { id: 'htaccess-generator', name: 'Htaccess Redirect Code Generator', description: 'Create Apache redirect rules for old paths, migrations, and canonical URL changes.', category: 'developer', slug: '/developer/htaccess', icon: 'Route', tag: { label: 'Webmaster', tone: 'orange' }, highlight: '301 / 302', keywords: ['htaccess', 'redirect', 'apache'] },
  { id: 'robots-generator', name: 'Robots.txt Generator', description: 'Build a root-level robots.txt file with user-agent, allow, disallow, and sitemap directives.', category: 'developer', slug: '/developer/robots', icon: 'Bot', tag: { label: 'SEO', tone: 'green' }, highlight: 'Crawler rules', keywords: ['robots', 'crawler', 'seo'] },
  { id: 'domain-age', name: 'Domain Authority/Age Checker', description: 'Check public RDAP registration age and status. This tool does not fabricate or claim a third-party SEO authority score without a configured provider.', category: 'developer', slug: '/developer/domain-age', icon: 'Globe2', tag: { label: 'Live lookup', tone: 'orange' }, highlight: 'Clear status', keywords: ['domain', 'age', 'authority', 'rdap'] },
  { id: 'social-share', name: 'Website Social Share Link Generator', description: 'Generate ready-to-use share links for Facebook, X, and LinkedIn from a page URL and title.', category: 'developer', slug: '/developer/social-share', icon: 'Share2', tag: { label: 'No upload', tone: 'violet' }, highlight: 'Copy-ready', keywords: ['social', 'share', 'facebook', 'linkedin'] },
  { id: 'json-csv', name: 'JSON to CSV Converter', description: 'Convert an object or array of objects into escaped CSV with consistent columns.', category: 'developer', slug: '/developer/json-csv', icon: 'Braces', tag: { label: 'No upload', tone: 'violet' }, highlight: 'Data-ready', keywords: ['json', 'csv', 'api', 'data'] },
  { id: 'regex-cheat', name: 'Regex Cheat Sheet & Tester', description: 'Test a regular expression against sample text and review common pattern building blocks.', category: 'developer', slug: '/developer/regex', icon: 'Code2', tag: { label: 'No upload', tone: 'violet' }, highlight: 'Live matches', keywords: ['regex', 'pattern', 'tester'] },
  { id: 'sql-formatter', name: 'SQL Query Formatter', description: 'Turn dense SQL into a readable multi-line query for review and debugging.', category: 'developer', slug: '/developer/sql', icon: 'Database', tag: { label: 'No upload', tone: 'violet' }, highlight: 'Readable SQL', keywords: ['sql', 'database', 'query'] },
  { id: 'yaml-validator', name: 'YAML Validator', description: 'Check common YAML key, list, and indentation structure without executing document tags.', category: 'developer', slug: '/developer/yaml', icon: 'FileCheck2', tag: { label: 'No upload', tone: 'violet' }, highlight: 'Safe parse check', keywords: ['yaml', 'config', 'devops'] },
  { id: 'crontab-generator', name: 'Crontab Expression Generator', description: 'Build a five-field cron expression and see a plain-language schedule summary.', category: 'developer', slug: '/developer/crontab', icon: 'Clock3', tag: { label: 'No upload', tone: 'violet' }, highlight: 'Human-readable', keywords: ['cron', 'crontab', 'schedule'] },
  { id: 'timezone-converter', name: 'Time Zone Converter', description: 'Convert a date and time between IANA time zones for international and remote teams.', category: 'developer', slug: '/developer/timezone', icon: 'Globe', tag: { label: 'Remote work', tone: 'violet' }, highlight: 'IANA zones', keywords: ['timezone', 'remote', 'international'] },
  { id: 'svg-png', name: 'SVG to PNG Converter', description: 'Render SVG markup in the browser and prepare a PNG export without uploading the source.', category: 'image', slug: '/image/svg-to-png', icon: 'Image', tag: { label: 'Browser', tone: 'green' }, highlight: 'Local render', keywords: ['svg', 'png', 'image'] },
  { id: 'flexbox-generator', name: 'CSS Flexbox Generator', description: 'Visually choose flex direction, alignment, and gap, then copy the generated CSS.', category: 'developer', slug: '/developer/flexbox', icon: 'LayoutDashboard', tag: { label: 'No upload', tone: 'violet' }, highlight: 'Visual CSS', keywords: ['css', 'flexbox', 'layout'] },
  { id: 'utm-builder', name: 'UTM Link Builder', description: 'Build consistent campaign URLs with source, medium, campaign, and content parameters.', category: 'developer', slug: '/developer/utm', icon: 'Link2', tag: { label: 'Marketing', tone: 'orange' }, highlight: 'Campaign-ready', keywords: ['utm', 'campaign', 'analytics', 'marketing'] },
  { id: 'subnet-calc', name: 'Subnet Calculator', description: 'Calculate IPv4 network, broadcast, usable host range, address count, and CIDR prefix.', category: 'developer', slug: '/developer/subnet', icon: 'Network', tag: { label: 'No upload', tone: 'violet' }, highlight: 'CIDR-aware', keywords: ['subnet', 'cidr', 'ipv4', 'network'] },
];

export const QUICK_FILTERS: QuickFilter[] = [
  { id: 'all', label: 'All' },
  { id: 'ai', label: 'AI-powered', match: t => t.badge === 'AI' || t.tag?.label === 'AI' },
  { id: 'noupload', label: 'No upload', match: t => t.tag?.label === 'No upload' || t.tag?.label === 'Private' || t.tag?.label === 'Browser' },
  { id: 'finance', label: 'Finance', match: t => t.category === 'calculator' },
  { id: 'new', label: 'New', match: t => ['compound-interest','crypto-roi','mortgage-amortization','salary-after-tax','freelance-rate','investment-return','percentage-calc','sitemap-generator','htaccess-generator','robots-generator','domain-age','social-share','json-csv','regex-cheat','sql-formatter','yaml-validator','crontab-generator','timezone-converter','svg-png','flexbox-generator','utm-builder','subnet-calc'].includes(t.id) },
];
